theme: jekyll-theme-dinky
title: Welcome to the Homepage
description: EPPS 6323 Website
collections:
 assignments:
  order:
   - Assignment_1.md
   - Assignment_2.md
   - Assignment_3.md
   - Assignment_4.md
   - Assignment_5.md
   
